### ISSUE TITLE
[Bug]: locally "Custom Native iOS Code" not working (Capacitor 6)

### ISSUE THREAD

**Issue by rricamar** [ionic-team/capacitor-docs#275]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.1
  @capacitor/core: 5.7.1
  @capacitor/android: 5.7.1
  @capacitor/ios: 5.7.1

Installed Dependencies:

  @capacitor/cli: 6.0.0-rc.0
  @capacitor/core: 6.0.0-rc.0
  @capacitor/android: 6.0.0-rc.0
  @capacitor/ios: 6.0.0-rc.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
npm 10.2.4
node v20.11.1
pod 1.14.3
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

I was trying Capacitor 6 today and just discovered that the local Echo plugin from the tutorial is not working (https://capacitorjs.com/docs/ios/custom-code). If I rollback to Capacitor 5.7.1 it works as usual.

_Note: I'm using it directly through `window.Capacitor.Plugins.Echo` (which is now `undefined`)._

_Note 2: Another plugin installed and created with https://github.com/ionic-team/create-capacitor-plugin works fine._

_Note 3: On Android is working well._

### Expected Behavior

Plugin invocation should work as described in the docs.

### Project Reproduction

N/A

**Comment by jcesarmobile** [comment]
Capacitor 6 removes the automatic plugin registration for iOS, so for non npm plugins, users will have to call `registerPlugin` as on Android.

That would require using a custom `CAPBridgeViewController` subclass as explained here

https://capacitorjs.com/docs/ios/viewcontroller

And override it's `capacitorDidLoad` to register the plugin there, something like this:

```
override open func capacitorDidLoad() {
    bridge?.registerPluginInstance(EchoPlugin())
}
```

Moving to capacitor-docs since we have to write docs for it.

**Comment by xbisa** [comment]
I'm facing the same issue for NPM Capacitor 6 plugins such as the toast and local-notifications Capacitor plugins on iOS only. As far as I understand they don't need to be registered. Is anyone else having this issue?

**Comment by rricamar** [comment]
> I'm facing the same issue for NPM Capacitor 6 plugins such as the toast and local-notifications Capacitor plugins on iOS only. As far as I understand they don't need to be registered. Is anyone else having this issue?

Hello @xbisa, after updating to Capacitor 6 the `local-notifications` plugin worked as expected with no additional modifications 🤔 maybe you need to open a new issue for this 👍

**Comment by xbisa** [comment]
Hi @rricamar 
Thank you for taking time to test it.
I'm trying out XCode on macOS in the cloud. I notice that npx cap sync it updates my Podfile.lock. This was not happening on my Windows dev environment.
If it still fails, I will consider opening a new issue.

**Comment by xbisa** [comment]
Hi @rricamar
I have tested in XCode on several iOS devices. Everything okay.
I have tested on appetize.io on several iOS devices. Everything okay.
Then I use appflow to build a package and deploy it to TestFlight, install it on my iPhone 8+ where the plugins return error code UNIMPLEMENTED.
I have contacted IONIC support who think the issue may be related to issue you were having, but I don't have any custom Capacitor plugins, so it makes no sense.
I've been struggling for two weeks with this issue which is a big show stopper for me on the iOS platform, because it means I can't deploy any new features.
Any feedback feedback from anyone regarding my issue is appreciated.

**Comment by faguilera85** [comment]
I'm facing the same issue with `"@capacitor-community/admob": "^6.0.0"`. When I call `await AdMob.initialize();` I get `{"code":"UNIMPLEMENTED"}` in the Xcode logs using the simulator on iPhone 15 Pro (iOS 17.4).
I really need help to understand how to proceed please, I've been blocked for more than a week already.

**Comment by FernetB** [comment]
Hi!

I did everything that the docs says, but im getting this error 

"Could not cast value of type 'UIViewController' (0x1358d2330) to 'Capacitor.CAPBridgeViewController'"

Someone had the same problem?
